# Generated by Django 6.1 on 2026-09-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0002_alter_nodoservidor_direccion_ip_registroauditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='infraestructura.nodoservidor', verbose_name='Servidor'),
        ),
    ]
