# Generated by Django 6.1 on 2026-09-08 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0003_alter_registroauditoria_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Severidad')),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Resuelta?')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='infraestructura.nodoservidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Incidencia de Servidor',
                'verbose_name_plural': 'Incidencias de Servidores',
                'ordering': ('-fecha_reporte',),
            },
        ),
    ]
