# Generated by Django 6.1 on 2026-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_host', models.CharField(max_length=100, unique=True, verbose_name='Hostname')),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('motor_contenedores', models.CharField(choices=[('docker', 'Docker'), ('podman', 'Podman'), ('lxc', 'LXC Linux Containers'), ('ninguno', 'Sin contenedores')], default='podman', max_length=20, verbose_name='Motor de Contenedores')),
                ('proxy_inverso', models.BooleanField(default=True, verbose_name='¿Enrutado por Nginx?')),
                ('en_produccion', models.BooleanField(default=True, verbose_name='Estado Producción')),
                ('fecha_despliegue', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nodo de Servidor',
                'verbose_name_plural': 'Flota de Servidores',
            },
        ),
    ]
